# file: even_fibonacci_euler_adupree.py
# description: find the sum of even fibonacci numbers
# authors: Alex DuPree
# date: 11/17/2017
# compiler: Python 3.6

"""
FROM PROJECT EULER:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def even_fib_sum(n):
    a, b = 0, 1
    even_num = []
    while a < n:
        if a % 2 == 0:
            even_num.append(a)
        a, b = b, a + b
    return sum(even_num)


print(even_fib_sum(4000000))
